env:
  - 
  - lower_bound_dependencies=1 
  - ghc_version=7.6.1
  - ghc_version=7.6.1
    lower_bound_dependencies=1
  - postgres_version=8.3.0
    postgres_integer_datetimes=0
  - postgres_version=8.3.0
    postgres_integer_datetimes=1
  - postgres_version=9.4rc1
    postgres_integer_datetimes=0

install:
  # Set up the Shell to treat the semicolon as &&
  - set -o pipefail && set -e
  # Install GHC and Cabal
  - 
    ghc_version=${ghc_version=7.8.1};
    travis_retry sudo add-apt-repository -y ppa:hvr/ghc;
    travis_retry sudo apt-get update;
    travis_retry sudo apt-get install cabal-install-1.18 ghc-$ghc_version;
    export PATH=/opt/ghc/$ghc_version/bin:/opt/cabal/1.18/bin:$PATH;
  # Update the Cabal database
  - cabal update
  # Switch to the distro:
  - 
    export pkg_name=$(cabal info . | awk '{print $2;exit}');
    cabal sdist;
    cd dist;
    tar xzvf $pkg_name.tar.gz;
    cd $pkg_name;
  # Install the lower bound dependencies
  - 
    if [ $lower_bound_dependencies -eq 1 ];
    then
      cabal install "transformers == 0.2.*";
      cabal install "bytestring == 0.10.0.0";
      cabal install "text == 1.0.*";
      cabal install "attoparsec == 0.10.*";
      cabal install "scientific == 0.2.*";
      cabal install "QuickCheck == 2.6.*";
    fi;
  # Install the remaining dependencies
  - 
    cabal install happy;
    cabal install --only-dependencies --enable-tests --enable-benchmarks --avoid-reinstalls
  # Configure and build
  - 
    cabal configure --enable-tests --enable-benchmarks;
    cabal build
  # Optionally install an arbitrary PostgreSQL version:
  - 
    if [ $postgres_version ];
    then
      export project_dir=$(pwd);
      sudo /etc/init.d/postgresql stop;
      wget https://ftp.postgresql.org/pub/source/v$postgres_version/postgresql-$postgres_version.tar.gz;
      tar xzvf postgresql-$postgres_version.tar.gz;
      cd "postgresql-$postgres_version";
      if [ $postgres_integer_datetimes -eq 1 ];
      then
        sudo ./configure --enable-integer-datetimes --without-readline;
      else
        sudo ./configure --disable-integer-datetimes --without-readline;
      fi;
      sudo make;
      sudo make install;
      sudo mkdir /usr/local/pgsql/data;
      sudo chown postgres /usr/local/pgsql/data;
      sudo mkdir /usr/local/pgsql/log;
      sudo chown postgres /usr/local/pgsql/log;
      sudo -u postgres /usr/local/pgsql/bin/initdb -D /usr/local/pgsql/data;
      sudo -u postgres 
        /usr/local/pgsql/bin/pg_ctl start 
          -D /usr/local/pgsql/data 
          -l /usr/local/pgsql/log/main.log
          -o "-h localhost -p 5432";
      sleep 3;
      sudo -u postgres /usr/local/pgsql/bin/createdb postgres || true;
      cd $project_dir;
    fi;

script:
  - cabal test --show-details=always ||
    { 
      echo "Test failed. Here's the Postgres' log:";
      sudo cat /usr/local/pgsql/log/main.log;
      exit 1;
    }
